os: osx
language: android

before_install:
  - export ANDROID_HOME=/usr/local/share/android-sdk
  - export ANDROID_NDK=/usr/local/share/android-sdk/ndk-bundle
  - export PATH=$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
  - brew update > /dev/null;
  - brew install Caskroom/cask/android-sdk
  # Tools
  - echo y | sdkmanager 'tools'
  # Platform tools
  - echo y | sdkmanager 'platform-tools'
  # SDKs
  - echo y | sdkmanager 'platforms;android-25'
  # build tools
  - echo y | sdkmanager 'build-tools;25.0.3'
  # Extras
  - echo y | sdkmanager 'extras;android;m2repository'
  - echo y | sdkmanager 'extras;google;google_play_services'
  - echo y | sdkmanager 'extras;google;m2repository'
  # NDK
  - echo y | sdkmanager 'ndk-bundle'
   
script:
  - chmod +x ./gradlew
  - ./gradlew dependencies
  - ./gradlew test
  - ./gradlew build --stacktrace
