version: '{build}'

clone_folder: c:\projects\citra-android

init:
  - cd \
  - appveyor DownloadFile http://dl.google.com/android/android-sdk_r25.2.3-windows.zip
  - 7z x android-sdk_r25.2.3-windows.zip > nul
  - appveyor DownloadFile http://dl.google.com/android/repository/android-ndk-r13b-windows-x86_64.zip
  - 7z x android-ndk-r13b-windows-x86_64.zip > nul
  - cd c:\projects\citra-android

environment:
  ANDROID_NDK_HOME: C:\android-ndk-r13b
  ANDROID_HOME: C:\android-sdk-windows
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - git submodule update --init --recursive
  - echo y | C:\android-sdk-windows\tools\android.bat update sdk --no-ui --all --filter android-25
  - echo y | C:\android-sdk-windows\tools\android.bat update sdk --no-ui --all --filter platform-tools
  - echo y | C:\android-sdk-windows\tools\android.bat update sdk --no-ui --all --filter tools
  - echo y | C:\android-sdk-windows\tools\android.bat update sdk --no-ui --all --filter build-tools-25.0.2
  - echo y | C:\android-sdk-windows\tools\android.bat update sdk --no-ui --all --filter extra-google-m2repository
  - echo y | C:\android-sdk-windows\tools\android.bat update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | C:\android-sdk-windows\tools\android.bat update sdk --no-ui --all --filter extra-google-google_play_services
  - echo y | C:\android-sdk-windows\tools\android.bat update sdk --no-ui --all --filter extra-android-support

build_script:
  - cd c:\projects\citra-android
  - gradlew dependencies
  - gradlew test
  - gradlew build

test: off
